import { doesNotThrow, equal, throws } from "node:assert/strict";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { describe, it } from "node:test";
import {
  MATRIX_MEGOLM_ALGORITHM,
  MATRIX_OLM_ALGORITHM,
  MatrixKeyUploadValidationError,
  assertMatrixEd25519PublicKey,
  encodeMatrixCanonicalJson,
  parseInitialMatrixKeyUpload,
  parseMatrixKeyUpload,
  verifyMatrixSignedObject
} from "./matrix-key-upload";

const USER_ID = "@u11111111111141118111111111111111:sinochat.invalid";
const DEVICE_ID = "D22222222222242228222222222222222";
const KEY_ID = `ed25519:${DEVICE_ID}`;
const ERROR_CODE = "MATRIX_TEST_SIGNATURE_INVALID";
const IDENTITY = Buffer.from(`01${"00".repeat(31)}`, "hex");
const ORDER_FOUR = Buffer.alloc(32);
const ORDER_TWO = Buffer.from(`ec${"ff".repeat(30)}7f`, "hex");
const NON_CANONICAL_Y = Buffer.from(`ee${"ff".repeat(30)}7f`, "hex");
const NON_CANONICAL_SIGN = Buffer.from(`01${"00".repeat(30)}80`, "hex");
const INVALID_CURVE_POINT = Buffer.from(`02${"00".repeat(31)}`, "hex");
// RFC 8032's encoded base point: test-only public key for the known scalar 1.
const BASE_POINT = Buffer.from(`58${"66".repeat(31)}`, "hex");
const SCALAR_ORDER =
  2n ** 252n + 27742317777372353535851937790883648493n;

describe("Matrix Ed25519 strict public points", () => {
  it("accepts a public key generated by the standard signer", () => {
    const { publicKey } = generateKeyPairSync("ed25519");
    const bytes = publicKey.export({ format: "der", type: "spki" }).subarray(-32);
    doesNotThrow(() => assertMatrixEd25519PublicKey(base64(bytes), ERROR_CODE));
  });

  for (const [name, bytes] of [
    ["identity", IDENTITY],
    ["order four", ORDER_FOUR],
    ["order two", ORDER_TWO],
    ["non-canonical y coordinate", NON_CANONICAL_Y],
    ["non-canonical sign bit", NON_CANONICAL_SIGN],
    ["off-curve encoding", INVALID_CURVE_POINT]
  ] as const) {
    it(`rejects ${name} with the caller's safe error code`, () => {
      throwsValidation(
        () => assertMatrixEd25519PublicKey(base64(bytes), ERROR_CODE),
        ERROR_CODE
      );
    });
  }

  it("rejects malformed base64, lengths and non-canonical trailing bits", () => {
    const encoded = base64(BASE_POINT);
    for (const value of ["", `${encoded}=`, encoded.slice(1), "!".repeat(43), "A".repeat(42) + "B"]) {
      throwsValidation(() => assertMatrixEd25519PublicKey(value, ERROR_CODE), ERROR_CODE);
    }
  });
});

describe("Matrix Ed25519 strict signed objects", () => {
  it("preserves signatures from standard Ed25519 and the Matrix canonical JSON boundary", () => {
    const { publicKey, privateKey } = generateKeyPairSync("ed25519");
    const core = { key: base64(Buffer.alloc(32, 7)) };
    const signature = sign(null, encodeMatrixCanonicalJson(core), privateKey);
    const value = signed(core, signature);
    const key = publicKey.export({ format: "der", type: "spki" }).subarray(-32);
    doesNotThrow(() => verifyMatrixSignedObject(value, USER_ID, KEY_ID, base64(key), ERROR_CODE));
    throwsValidation(
      () => verifyMatrixSignedObject({ ...value, key: base64(Buffer.alloc(32, 8)) }, USER_ID, KEY_ID, base64(key), ERROR_CODE),
      ERROR_CODE
    );
  });

  it("rejects the constant identity signature without a private key", () => {
    const value = signed({ key: base64(Buffer.alloc(32, 7)) }, identitySignature());
    throwsValidation(() => verifyMatrixSignedObject(value, USER_ID, KEY_ID, base64(IDENTITY), ERROR_CODE), ERROR_CODE);
  });

  it("rejects a weak R even when A is a normal prime-order point and the equation verifies", () => {
    const core = { key: base64(Buffer.alloc(32, 7)) };
    // Deliberately degenerate nonce r=0 with known scalar a=1. This fixture
    // passes OpenSSL's equation alone; dalek's strict profile rejects weak R.
    const signature = zeroNonceSignature(encodeMatrixCanonicalJson(core));
    const value = signed(core, signature);
    throwsValidation(() => verifyMatrixSignedObject(value, USER_ID, KEY_ID, base64(BASE_POINT), ERROR_CODE), ERROR_CODE);
  });

  for (const [name, r] of [
    ["non-canonical R coordinate", NON_CANONICAL_Y],
    ["non-canonical R sign bit", NON_CANONICAL_SIGN],
    ["off-curve R", INVALID_CURVE_POINT],
    ["order-four R", ORDER_FOUR]
  ] as const) {
    it(`rejects ${name}`, () => {
      const signature = Buffer.concat([r, Buffer.alloc(32)]);
      throwsValidation(
        () => verifyMatrixSignedObject(signed({ key: base64(Buffer.alloc(32, 7)) }, signature), USER_ID, KEY_ID, base64(BASE_POINT), ERROR_CODE),
        ERROR_CODE
      );
    });
  }
});

describe("Matrix key upload cannot admit forgeable Ed25519 identities", () => {
  it("rejects an initial device and OTK signed only with the constant identity signature", () => {
    const signatures = signed({}, identitySignature()).signatures;
    const body = {
      device_keys: {
        user_id: USER_ID,
        device_id: DEVICE_ID,
        algorithms: [MATRIX_OLM_ALGORITHM, MATRIX_MEGOLM_ALGORITHM],
        keys: {
          [KEY_ID]: base64(IDENTITY),
          [`curve25519:${DEVICE_ID}`]: base64(Buffer.alloc(32, 7))
        },
        signatures
      },
      one_time_keys: {
        "signed_curve25519:weak_fixture": {
          key: base64(Buffer.alloc(32, 8)),
          signatures
        }
      }
    };
    throwsValidation(() => parseInitialMatrixKeyUpload(body, { userId: USER_ID, deviceId: DEVICE_ID }));
  });

  it("rejects OTK replenishment against a weak previously stored public key", () => {
    const oneTimeKey = signed({ key: base64(Buffer.alloc(32, 8)) }, identitySignature());
    throwsValidation(() => parseMatrixKeyUpload(
      { one_time_keys: { "signed_curve25519:weak_fixture": oneTimeKey } },
      { userId: USER_ID, deviceId: DEVICE_ID, existingEd25519PublicKey: base64(IDENTITY) }
    ));
  });

  it("rejects an OTK's degenerate R against a non-weak stored public key", () => {
    const core = { key: base64(Buffer.alloc(32, 8)) };
    const oneTimeKey = signed(core, zeroNonceSignature(encodeMatrixCanonicalJson(core)));
    throwsValidation(() => parseMatrixKeyUpload(
      { one_time_keys: { "signed_curve25519:weak_r_fixture": oneTimeKey } },
      { userId: USER_ID, deviceId: DEVICE_ID, existingEd25519PublicKey: base64(BASE_POINT) }
    ), "MATRIX_CURVE_KEY_SIGNATURE_INVALID");
  });
});

function signed<T extends object>(core: T, signature: Buffer): T & { signatures: Record<string, Record<string, string>> } {
  return { ...core, signatures: { [USER_ID]: { [KEY_ID]: base64(signature) } } };
}

function identitySignature(): Buffer {
  return Buffer.concat([IDENTITY, Buffer.alloc(32)]);
}

/** Adversarial regression fixture only; never a production signing function. */
function zeroNonceSignature(message: Buffer): Buffer {
  const hash = createHash("sha512").update(IDENTITY).update(BASE_POINT).update(message).digest();
  const scalar = BigInt(`0x${Buffer.from(hash).reverse().toString("hex")}`) % SCALAR_ORDER;
  const encodedScalar = Buffer.from(scalar.toString(16).padStart(64, "0"), "hex").reverse();
  return Buffer.concat([IDENTITY, encodedScalar]);
}

function base64(bytes: Buffer): string {
  return bytes.toString("base64").replace(/=+$/u, "");
}

function throwsValidation(action: () => unknown, code?: string): void {
  throws(action, (error: unknown) => {
    if (!(error instanceof MatrixKeyUploadValidationError)) return false;
    if (code !== undefined) equal(error.code, code);
    equal(error.message, error.code);
    return true;
  });
}
