/**
 * Códigos estables para auditar acciones administrativas ordinarias.
 *
 * Estas operaciones no recaban texto libre del administrador. Los motivos
 * redactados se reservan para reportes, evidencia, resoluciones y bloqueos.
 */
export const ADMIN_AUTOMATIC_REASON = {
  CASHIER_ONBOARDING_INVITATION_CREATED:
    "ADMIN_CASHIER_ONBOARDING_INVITATION_CREATED",
  CASHIER_ONBOARDING_INVITATION_REVOKED:
    "ADMIN_CASHIER_ONBOARDING_INVITATION_REVOKED",
  USER_UPDATED: "ADMIN_USER_UPDATED",
  USER_DELETED: "ADMIN_USER_DELETED",
  CASHIER_PASSWORD_RESET: "ADMIN_CASHIER_PASSWORD_RESET",
  CASHIER_APPROVED: "ADMIN_CASHIER_APPROVED",
  USER_SUSPENDED: "ADMIN_USER_SUSPENDED",
  USER_REACTIVATED: "ADMIN_USER_REACTIVATED",
  SUBSCRIPTION_ACTIVATED: "ADMIN_SUBSCRIPTION_ACTIVATED",
  SUBSCRIPTION_DEACTIVATED: "ADMIN_SUBSCRIPTION_DEACTIVATED",
  CLIENT_REASSIGNED: "ADMIN_CLIENT_REASSIGNED"
} as const;

